import { StyleSheet } from 'react-native';

export const RegisStyle = StyleSheet.create({
    body: {
        backgroundColor: '#F9F9F9',
        height: '100%',
    },
    title: {
        color: 'blue',
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: 32,
        color: '#010620',
        textAlign: 'center',
        marginTop: 30,
        marginBottom: 10,
    },
    descInput: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: 'normal',
        fontSize: 12,
        color: '#ADA9BB',
        marginLeft: 50,
        marginTop: 5,
    },
    inputLogin: {
        width: 310,
        height: 50,
        alignSelf: 'center',
        backgroundColor: '#F9F9F9',
        borderColor: '#ADA9BB',
        borderRadius: 10,
        color: 'black',
        borderWidth: 2,
    },
    buttonLogin: {
        backgroundColor: '#5784BA',
        marginTop: 25,
        width: 300,
        height: 50,
        borderRadius: 10,
        alignSelf: 'center',
        padding: 10,
        marginBottom: 5,
    },
    labelButtonLogin: {
        color: 'white',
        textAlign: 'center',
        fontSize: 16,
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: '500',
    },
    buttonLoginWithGoogle: {
        backgroundColor: '#000D4F14',
        marginTop: 10,
        width: 300,
        height: 50,
        borderRadius: 10,
        alignSelf: 'center',
    },
    labelButtonLoginWithGoogle: {
        color: 'black',
        textAlign: 'center',
        fontSize: 16,
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: '500',
        marginTop: '-10%',
        marginLeft: '5%',
    },
    forgotPass: {
        color: 'black',
        position: 'absolute',
        width: 97,
        height: 14,
        left: 250,
        top: 270,
        fontFamily: 'Roboto',
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: 12,
    },
    logoBtn: {
        width: 30,
        marginLeft: '15%',
        marginTop: '2%',
    },
    Login: {
        fontFamily: 'Kanit',
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: 12,
        color: '#ADA9BB',
        marginTop: 30,
        textAlign: 'center',
    },
    link: { color: 'blue',}

});